//  =============== BEGIN ASSESSMENT HEADER ================
/// make file for HW2 
/// 
//  ================== END ASSESSMENT HEADER ===============

all: main.cpp 
    source /opt/rh/devtoolset-2/enable
	g++ -std=c++11 -Wall -Werror -pedantic main.cpp
	
run: a.out users1.txt data1.txt 
	./a.out users1.txt data1.txt